# Generated by Django 5.2.14 on 2026-05-21 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0004_start_at_and_plan_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.CharField(max_length=64)),
                ("trip_current_label", models.CharField(max_length=255)),
                ("trip_pickup_label", models.CharField(max_length=255)),
                ("trip_dropoff_label", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[("multi_page", "Multi-page"), ("single_page", "Single-page")],
                        max_length=16,
                    ),
                ),
                ("sheet_count", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exports",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user_id", "-created_at"], name="exports_tri_user_id_2858e5_idx"
                    ),
                    models.Index(fields=["trip"], name="exports_tri_trip_id_8d76a9_idx"),
                ],
            },
        ),
    ]
